name: gemini_comp
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  calendar_date_picker2: ^1.1.5
  cloud_firestore: ^5.1.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  fancy_shimmer_image: ^2.0.3
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gemini: ^2.0.4
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.6.4
  google_generative_ai: ^0.4.3
  google_maps_flutter: ^2.7.0
  intl: ^0.19.0
  readmore: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_auth: ^5.1.2
  fluttertoast: ^8.2.4

dev_dependencies:
  build_runner: ">=2.3.0 <4.0.0"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/svgs/
    - assets/images/pngs/
    - assets/lang/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
