// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDG9W07fGE17z7NoWScg4Xmt9hri39m29Q',
//     appId: '1:7251537623:web:5d9b1f295757c2180b0a92',
//     messagingSenderId: '7251537623',
//     projectId: 'doctory-848a9',
//     authDomain: 'doctory-848a9.firebaseapp.com',
//     storageBucket: 'doctory-848a9.appspot.com',
//     measurementId: 'G-MGTJQ54RR1',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA9iRFthvMja-SqFEDYoPXRUv8kQ3paJEc',
//     appId: '1:7251537623:android:8d8cea728b0a7c3c0b0a92',
//     messagingSenderId: '7251537623',
//     projectId: 'doctory-848a9',
//     storageBucket: 'doctory-848a9.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBH2LzN2u25ClTAioykA2s18GOJGWbGruo',
//     appId: '1:7251537623:ios:86bd5770f9f6fcba0b0a92',
//     messagingSenderId: '7251537623',
//     projectId: 'doctory-848a9',
//     storageBucket: 'doctory-848a9.appspot.com',
//     iosBundleId: 'com.example.geminiComp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBH2LzN2u25ClTAioykA2s18GOJGWbGruo',
//     appId: '1:7251537623:ios:86bd5770f9f6fcba0b0a92',
//     messagingSenderId: '7251537623',
//     projectId: 'doctory-848a9',
//     storageBucket: 'doctory-848a9.appspot.com',
//     iosBundleId: 'com.example.geminiComp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDG9W07fGE17z7NoWScg4Xmt9hri39m29Q',
//     appId: '1:7251537623:web:6cca12ea3b7d96fb0b0a92',
//     messagingSenderId: '7251537623',
//     projectId: 'doctory-848a9',
//     authDomain: 'doctory-848a9.firebaseapp.com',
//     storageBucket: 'doctory-848a9.appspot.com',
//     measurementId: 'G-QHZXM9JG8C',
//   );
// }
